appName = "id-generator"
profile = "dev"

port = 8080
router = "/id/next"
date_center_id = 1
worker_id = 1

#zookeeper
nodePath = "/your_application_path/node-"
connectString = "192.168.1.1:2181,192.168.1.2:2181,192.168.1.3:2181"
